# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 16712-azure-devops

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Chaincode_Java_Creds

stages:
  - stage: Build_and_test
    jobs:
      - job: javadoc
        steps:
        - checkout: self
          persistCredentials: true
        - script: env | sort
          displayName: 'Wassup'
        - script: ./gradlew javadoc
          displayName: 'Build JavaDoc'
        - script: |
            git remote -v
            git fetch origin
            git branch -r
            git checkout -b gh-pages origin/gh-pages
            mkdir -p master/api
            cp -r fabric-chaincode-shim/build/docs/javadoc/* master/api
          displayName: 'Update gh-pages content'
        - script: |
            git config core.pager cat
            git config -l
            echo git config --local user.name "Azure Pipelines"
            echo git config --local user.email "azuredevops@microsoft.com"
            git status
            git add -A
            git status
            git commit -m "Publishing GitHub Pages [skip ci]"
            git status
            git log -1
            echo git push origin gh-pages
          displayName: 'Add gh-pages commit'
