# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 16712-azure-devops

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Chaincode_Java_Creds

stages:
  - stage: Build_and_test
    jobs:
      - job: javadoc
        steps:
        - script: env | sort
          displayName: 'Wassup'
        - script: ./gradlew javadoc
          displayName: 'Build JavaDoc'
        - script: |
            git branch
            git remote -v
            git fetch origin
            git branch gh-pages origin/gh-pages
            cp -r fabric-chaincode-shim/build/docs/javadoc/* master/api
          displayName: 'Update gh-pages content'
        - script: |
            git config --local user.name "Azure Pipelines"
            git config --local user.email "azuredevops@microsoft.com"
            git add .
            git commit -m "Publishing GitHub Pages [skip ci]"
            git push origin gh-pages
          displayName: 'Add gh-pages commit'
