# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 16712-azure-devops

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Chaincode_Java_Creds

stages:
  - stage: Build_and_test
    jobs:
      - job: javadoc
        steps:
        - checkout: self
          persistCredentials: true
        - script: env | sort
          displayName: 'Wassup'
        - script: ./gradlew javadoc
          displayName: 'Build JavaDoc'
        - script: |
            if [ -d docs ]; then
              mkdir gh-pages
              cp -r docs/* gh-pages
            fi
            mkdir -p gh-pages/_includes
            touch gh-pages/_config.yml gh-pages/404.md gh-pages/index.md gh-pages/_includes/footer.html gh-pages/_includes/header.html gh-pages/_includes/javadocs.html
          displayName: 'Copy shared doc'
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/16712-azure-devops')
        - script: |
            git remote -v
            git fetch origin
            git branch -r
            git checkout -b gh-pages origin/gh-pages
            mkdir -p master/api
            cp -r fabric-chaincode-shim/build/docs/javadoc/* master/api
            if [ -d gh-pages ]; then
              find . -maxdepth 1 ! \( -name [.]* -o -name 'gh-pages' -o -name 'master' -o -name 'release-*' \) -exec rm -rf {} \;
              cp -r gh-pages/* .
              rm -rf gh-pages
            fi
          displayName: 'Update gh-pages content'
        - script: |
            git config core.pager cat
            git config --local user.name "Azure Pipelines"
            git config --local user.email "azuredevops@microsoft.com"
            git config -l
            git status
            git add -A
            git status
            git commit -m "Publishing GitHub Pages [skip ci]"
            git status
            git log -2
            echo git push origin gh-pages
          displayName: 'Add gh-pages commit'
